//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.Lines = new HashSet<Line>();
            this.Lines1 = new HashSet<Line>();
        }
    
        public int Id { get; set; }
        public string IdUnique { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<Line> Lines1 { get; set; }
    }
}
