//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader.DataNodeServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataNodeServiceClient.IDataNodeService")]
    public interface IDataNodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataNodeService/SaveNodes", ReplyAction="http://tempuri.org/IDataNodeService/SaveNodesResponse")]
        void SaveNodes(Entities.Node[] nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataNodeService/SaveNodes", ReplyAction="http://tempuri.org/IDataNodeService/SaveNodesResponse")]
        System.Threading.Tasks.Task SaveNodesAsync(Entities.Node[] nodes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataNodeServiceChannel : DataLoader.DataNodeServiceClient.IDataNodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataNodeServiceClient : System.ServiceModel.ClientBase<DataLoader.DataNodeServiceClient.IDataNodeService>, DataLoader.DataNodeServiceClient.IDataNodeService {
        
        public DataNodeServiceClient() {
        }
        
        public DataNodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataNodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataNodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataNodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveNodes(Entities.Node[] nodes) {
            base.Channel.SaveNodes(nodes);
        }
        
        public System.Threading.Tasks.Task SaveNodesAsync(Entities.Node[] nodes) {
            return base.Channel.SaveNodesAsync(nodes);
        }
    }
}
