//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.AlgorithmClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlgorithmClient.IAlgorithmService")]
    public interface IAlgorithmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlgorithmService/GetShortestPath", ReplyAction="http://tempuri.org/IAlgorithmService/GetShortestPathResponse")]
        int[] GetShortestPath(int node1, int node2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlgorithmService/GetShortestPath", ReplyAction="http://tempuri.org/IAlgorithmService/GetShortestPathResponse")]
        System.Threading.Tasks.Task<int[]> GetShortestPathAsync(int node1, int node2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlgorithmServiceChannel : Client.AlgorithmClient.IAlgorithmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlgorithmServiceClient : System.ServiceModel.ClientBase<Client.AlgorithmClient.IAlgorithmService>, Client.AlgorithmClient.IAlgorithmService {
        
        public AlgorithmServiceClient() {
        }
        
        public AlgorithmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlgorithmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetShortestPath(int node1, int node2) {
            return base.Channel.GetShortestPath(node1, node2);
        }
        
        public System.Threading.Tasks.Task<int[]> GetShortestPathAsync(int node1, int node2) {
            return base.Channel.GetShortestPathAsync(node1, node2);
        }
    }
}
